TEC-4356: Adjustments on wizard component
vissimo-group/chardonnay pull request #22
Opened 2024-03-05 19:07 UTC by joelsalmeida

## Task link
[Task link from JIRA](https://evinobr.atlassian.net/browse/TEC-4356)

## Task description
Adjust Wizard components according to the design of the new cashback page.

## Roadmap
- [x] Adjustment on components
- [x] Stories update 

## Screenshots
![Screen Shot 2024-03-05 at 16 05 34](https://github.com/vissimo-group/chardonnay/assets/82453590/cb46238d-8f5f-40fe-ad55-285248cb96c0)

## Ambient to test
Local / Link to chromatic branch

2024-03-06 13:42 UTC, juninhokaponne approved these changes

2024-03-06 14:01 UTC, samuelvermeuln requested changes

2024-03-06 14:01 UTC, samuelvermeuln commented on src/components/Wizard/WizardProgressBar/index.tsx
> +  console.log('##### customColor: ', customColor)
Remover

2024-03-06 14:01 UTC, samuelvermeuln commented on src/components/Wizard/WizardProgressBar/style.tsx
> +    props.$customColor && `background-color: ${props.$customColor} !important;`}
${(props) =>
    background-color: ${props.$customColor} !important;}
    
    
    No need for conditional, if it says undefined or null the browser ignores it

2024-03-06 14:01 UTC, samuelvermeuln commented on src/components/Wizard/WizardProgressBar/style.tsx
> +    props.$customColor && `background-color: ${props.$customColor} !important;`}
check if necessary so !important
because if this prop comes after the one above it already overlaps

2024-03-06 14:01 UTC, samuelvermeuln commented on src/components/Wizard/WizardItem/WizardItemPoint/style.tsx
> +    props.$customColor &&
You can remove the conditional here too

2024-03-06 17:27 UTC, joelsalmeida commented on src/components/Wizard/WizardProgressBar/style.tsx
> +    props.$customColor && `background-color: ${props.$customColor} !important;`}
I removed "important" and kept the conditional. **Even with the browser ignoring the undefined property**, I think it is **easier to understand why the same property is being used twice** in the same style.

2024-03-07 13:34 UTC, samuelvermeuln approved these changes

2024-03-07 14:48 UTC, merged